[package]
name = "srng"
version = "0.1.0"
authors = ["Avril <flanchan@cumallover.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = "0.1"